version: "3.9"
services:
  db:
    image: mysql
    restart: 'no'
    environment:
      MYSQL_DATABASE: 'tks_engine'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - './db-prod:/var/lib/mysql'
      - './local:/var/lib/mysql-files'
      - ./app/database.sql:/docker-entrypoint-initdb.d/database.sql
    command: --init-file=/docker-entrypoint-initdb.d/database.sql

# WebUI for mysql database
  adminer:
    depends_on:
      - db
    image: adminer:4.8.1
    restart: 'no'
    ports:
      - "8081:8080"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root